package edu.osu.cse6341.lispInterpreter.tokenizer.tokens;

public enum TokenKind {
	CLOSE_TOKEN,
	EOF_TOKEN,
	ERROR_TOKEN,
	NUMERIC_TOKEN,
	OPEN_TOKEN,
	CAR_TOKEN,
	CDR_TOKEN,
	CONS_TOKEN,
	ATOM_TOKEN,
	INT_TOKEN,
	NULL_TOKEN,
	EQ_TOKEN,
	PLUS_TOKEN,
	MINUS_TOKEN,
	TIMES_TOKEN,
	LESS_TOKEN,
	GREATER_TOKEN;
}
